# Generated by Django 5.0 on 2024-07-27 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Enter the price as an integer (maximum 99999).', validators=[django.core.validators.MaxValueValidator(99999)])),
                ('image', models.ImageField(default='dish_pics/default.jpg', upload_to='dish_pics')),
            ],
        ),
    ]
