# Generated by Django 5.0 on 2024-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='dish_pics/default.jpg', upload_to='dish_pics'),
        ),
    ]
